import {chromium} from 'playwright';import {createServer} from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const mime={'.mjs':'text/javascript','.js':'text/javascript','.json':'application/json','.css':'text/css','.html':'text/html','.png':'image/png','.webp':'image/webp','.mp4':'video/mp4'};
const server=createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);const p=path.join(process.cwd(),pathname.endsWith('/')?pathname+'index.html':pathname);try{const stat=fs.statSync(p);res.setHeader('Content-Type',mime[path.extname(p)]||'image/jpeg');if(req.headers.range){const [startText,endText]=req.headers.range.replace('bytes=','').split('-'),start=Number(startText),end=endText?Number(endText):stat.size-1;res.writeHead(206,{'Content-Range':`bytes ${start}-${end}/${stat.size}`,'Accept-Ranges':'bytes','Content-Length':end-start+1});fs.createReadStream(p,{start,end}).pipe(res);}else{res.setHeader('Content-Length',stat.size);fs.createReadStream(p).pipe(res);}}catch{res.statusCode=404;res.end('Not found');}}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
const base=process.env.AKME_LIVE?'https://eduardoxyz22-maker.github.io/MULTIESPUMAS-VISCARRA/akme/':`http://127.0.0.1:${server.address().port}/akme/`;
const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});let errors=[];page.on('pageerror',e=>errors.push(e.message));let mediaRequests=[];page.on('request',r=>{if(/\.mp4(?:\?|$)/.test(r.url()))mediaRequests.push(r.url());});
const go=async file=>{await page.goto(base+file,{waitUntil:'domcontentloaded'});await page.evaluate(()=>document.documentElement.style.scrollBehavior='auto');};
await go('index.html');assert.equal(await page.locator('.highlight').count(),3);assert.equal(await page.locator('#cotizador').count(),0);assert.equal(await page.locator('.brand-logos li').count(),5);assert.equal(await page.locator('h1').count(),1);assert(!(await page.content()).includes('assets/portada.'));assert.equal(mediaRequests.length,0);await page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(async i=>{i.loading="eager";try{await i.decode()}catch{}}))});await page.screenshot({path:'final-home-desktop.png',fullPage:true});
await page.setViewportSize({width:390,height:844});await page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(async i=>{i.loading="eager";try{await i.decode()}catch{}}))});await page.screenshot({path:'final-home-mobile.png',fullPage:true});await page.locator('#menu-btn').click();await page.locator('#menu-panel a[href="servicios.html"]').click();await page.waitForURL('**/servicios.html');assert.equal(await page.locator('.faq-list details').count(),8);await page.goBack();assert.match(page.url(),/index.html$/);await page.goForward();assert.match(page.url(),/servicios.html$/);
for(const summary of await page.locator('.faq-list summary').all()){await summary.focus();await page.keyboard.press('Enter');assert(await summary.evaluate(e=>e.parentElement.open));await page.keyboard.press('Space');assert(!(await summary.evaluate(e=>e.parentElement.open)));}
await go('index.html#cotizador');await page.waitForURL('**/planes.html#cotizador');await page.locator('#quote-goals input').first().waitFor();assert.equal(await page.locator('#quote-name').textContent(),'SMART');
for(const [goal,plan,price] of [['presence','SMART',1800],['ads','ESENCIAL',2500],['optimization','COMPLETO',3900],['direction','PRO',4900],['integral','ELITE',7000]]){await page.locator('#quote-reset').click();await page.locator(`[name="quote-goal"][value="${goal}"]`).check();assert.equal(await page.locator('#quote-name').textContent(),plan);await page.locator('#quote-budget').fill(String(price-1));assert.equal(await page.locator('#quote-name').textContent(),'A tu medida.');await page.locator('#quote-budget').fill(String(price));assert.equal(await page.locator('#quote-name').textContent(),plan);}
await page.locator('#quote-reset').click();await page.locator('[data-key="videos"][data-delta="1"]').click();assert.equal(await page.locator('#quote-name').textContent(),'ESENCIAL');await page.locator('#quote-inspect').selectOption('smart');assert.match(await page.locator('#quote-reason').textContent(),/no cubre/);await page.locator('#quote-extras input[value="branding"]').check();assert.equal(await page.locator('#quote-name').textContent(),'A tu medida.');await page.locator('#quote-note').fill('Campaña de prueba');assert.match(decodeURIComponent(await page.locator('#quote-custom-wa').getAttribute('href')),/Campaña de prueba/);await page.locator('#quote-reset').click();await page.locator('#quote-copy').click();await page.waitForTimeout(100);assert(await page.locator('#quote-copy-status').textContent());await page.locator('#compare-btn').click();assert(await page.locator('#compare').isVisible());await page.locator('#compare-btn').click();
const ready=fs.existsSync('akme/portfolio.json');
if(ready){await go('index.html#trabajos');await page.waitForURL('**/portafolio.html');await page.locator('.brand-gallery').first().waitFor();assert.equal(await page.locator('.brand-gallery').count(),5);assert.equal(mediaRequests.length,0);const data=JSON.parse(fs.readFileSync('akme/portfolio.json'));assert(data.every(b=>b.items.length>=5));assert(!/manual|presentacion\.webp/i.test(JSON.stringify(data)));
for(const brand of data){const trigger=page.locator(`#proyecto-${brand.id} .gallery-bottom button`);await trigger.click();assert(await page.locator('#gallery-viewer').isVisible());for(let i=0;i<brand.items.length;i++){const item=brand.items[i];if(i>0)await page.locator('#gallery-next').click();assert.equal(await page.locator('#gallery-count').textContent(),`${i+1} / ${brand.items.length}`);if(item.type==='image')await page.locator('#gallery-media img').evaluate(e=>e.decode());else{const video=page.locator('#gallery-media video');await video.evaluate(e=>new Promise((resolve,reject)=>{if(e.readyState>=1)return resolve();e.addEventListener('loadedmetadata',resolve,{once:true});e.addEventListener('error',()=>reject(Error('Video failed')),{once:true})}));assert(await video.evaluate(e=>e.paused));await video.evaluate(e=>{e.muted=true;return e.play()});await page.waitForFunction(()=>document.querySelector("#gallery-media video")?.currentTime>0,{},{timeout:15000});}}await page.keyboard.press('Escape');assert(!(await page.locator('#gallery-viewer').isVisible()));assert(await trigger.evaluate(e=>document.activeElement===e));await page.waitForFunction(()=>!document.querySelector('#gallery-media video'));}
await page.setViewportSize({width:1440,height:1000});await go('portafolio.html');await page.locator('.brand-gallery').first().waitFor();await page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(async i=>{i.loading="eager";try{await i.decode()}catch{}}))});await page.screenshot({path:'final-portfolio-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(async i=>{i.loading="eager";try{await i.decode()}catch{}}))});await page.screenshot({path:'final-portfolio-mobile.png',fullPage:true});await page.reload();await page.locator('.brand-gallery').first().waitFor();}
for(const file of ['index.html','servicios.html','planes.html',...(ready?['portafolio.html']:[])]){await go(file);for(const width of [320,390,430,768,1440]){await page.setViewportSize({width,height:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Overflow ${file} ${width}`);}assert.equal(await page.locator('h1').count(),1);}
await go("servicios.html#equipo");await page.setViewportSize({width:1440,height:1000});await page.locator("#equipo").screenshot({path:"final-team-desktop.png"});await page.setViewportSize({width:390,height:844});await page.locator("#equipo").screenshot({path:"final-team-mobile.png"});assert.deepEqual(errors,[]);await browser.close();server.close();console.log('PASS: multipage navigation/direct URLs/back/forward/mobile menu; legacy quote URL; 5 exact plans/budgets/quantities/extras/manual comparison/reset/copy/WhatsApp; FAQ keyboard; responsive 320/390/768/1440; zero JS errors. Gallery complete: '+ready);
