import {chromium} from 'playwright';import {createServer} from 'node:http';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
const mime={'.mjs':'text/javascript','.js':'text/javascript','.json':'application/json','.css':'text/css','.html':'text/html','.png':'image/png','.webp':'image/webp','.mp4':'video/mp4'};
const server=createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);const p=path.join(process.cwd(),pathname.endsWith('/')?pathname+'index.html':pathname);try{const stat=fs.statSync(p);res.setHeader('Content-Type',mime[path.extname(p)]||'image/jpeg');if(req.headers.range){const [startText,endText]=req.headers.range.replace('bytes=','').split('-'),start=Number(startText),end=endText?Number(endText):stat.size-1;res.writeHead(206,{'Content-Range':`bytes ${start}-${end}/${stat.size}`,'Accept-Ranges':'bytes','Content-Length':end-start+1});fs.createReadStream(p,{start,end}).pipe(res);}else{res.setHeader('Content-Length',stat.size);fs.createReadStream(p).pipe(res);}}catch{res.statusCode=404;res.end('Not found');}}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
const base=process.env.AKME_LIVE?'https://eduardoxyz22-maker.github.io/MULTIESPUMAS-VISCARRA/akme/':`http://127.0.0.1:${server.address().port}/akme/`;
const browser=await chromium.launch({channel:'msedge'});const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:3});const page=await context.newPage();let errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route(/fonts\.(googleapis|gstatic)\.com/,r=>r.abort());
const settle=async()=>{await page.waitForTimeout(850)};
const go=async s=>{await page.goto(base+s,{waitUntil:'domcontentloaded'});if(s==='#trabajos')await page.waitForURL('**/portafolio.html');if(s==='#cotizador')await page.waitForURL('**/planes.html#cotizador');await settle();};
try{
for(const width of [320,390,430]){await page.setViewportSize({width,height:844});for(const file of ["index.html","portafolio.html","servicios.html","planes.html"]){await go(file);const brand=await page.locator(".top .brand").boundingBox(),nav=await page.locator(".top .nav").boundingBox();assert(brand.x+brand.width<=nav.x,"Header collision "+file+" "+width);assert(await page.locator(".top .brand-mascot").isVisible());assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator("#menu-btn").click();assert(await page.locator("#menu-panel a[href=\"servicios.html\"]").isVisible());assert.equal(await page.locator("#menu-panel a[href=\"planes.html#paquetes\"]").textContent(),"Paquetes");await page.locator("#menu-panel a[href=\"planes.html#paquetes\"]").click();await page.waitForURL("**/planes.html#paquetes");await settle();assert(Math.abs(await page.locator("#paquetes").evaluate(e=>e.getBoundingClientRect().top))<200);}}
await go("");for(const [label,url] of [["Ver servicios","servicios.html"],["Ver paquetes","planes.html#paquetes"]]){await page.locator(".hero-shortcuts a",{hasText:label}).click();await page.waitForURL("**/"+url);await page.goBack({waitUntil:"domcontentloaded"});await settle();assert.equal(await page.evaluate(()=>scrollY),0);}
console.log("PASS mascot header, Services/Packages routes and menu at 320/390/430");
for(const width of [320,390,430]){await page.setViewportSize({width,height:844});await go('');assert.equal(await page.evaluate(()=>scrollY),0);assert.equal(await page.evaluate(()=>document.activeElement.tagName),'BODY');assert(await page.locator('.portfolio-discovery a').isVisible());
for(const id of ['cosmetic','spadental']){await page.locator('.brand-logos a[href="portafolio.html#proyecto-'+id+'"]').click();await page.locator('#proyecto-'+id+' .gallery-bottom button').waitFor();await settle();const section=page.locator('#proyecto-'+id);assert(await section.isVisible());assert(await section.locator('.gallery-card').first().isVisible());const trigger=section.locator('.gallery-bottom button');await trigger.scrollIntoViewIfNeeded();await settle();const y=await page.evaluate(()=>scrollY);await trigger.click();const dlg=page.locator('#gallery-viewer');assert(await dlg.isVisible());assert.match(await page.locator('.gallery-close').textContent(),/Cerrar/);await dlg.evaluate(e=>e.scrollTop=e.scrollHeight);const rect=await page.locator('.gallery-close').boundingBox();assert(rect.y>=0&&rect.y+rect.height<844);await page.locator('.gallery-close').click();await page.waitForFunction(()=>!document.querySelector('#gallery-viewer').open);await settle();assert(await trigger.evaluate(e=>document.activeElement===e));assert(Math.abs(await page.evaluate(()=>scrollY)-y)<3,'Closing preserves page position');await page.locator('.portfolio-return a').click();await page.waitForURL('**/index.html');await settle();assert.equal(await page.evaluate(()=>scrollY),0);}
console.log('PASS mobile routes and close: '+width);}
for(const [hash,target] of [['#marcas','#marcas'],['#contacto','#contacto'],['#cotizador','#cotizador']]){await go(hash);const top=await page.locator(target).evaluate(e=>e.getBoundingClientRect().top);assert(Math.abs(top)<200,'Anchor '+hash+' top '+top);}
await go('#trabajos');assert.match(page.url(),/portafolio.html$/);assert.equal(await page.evaluate(()=>scrollY),0);
await go('');await page.evaluate(()=>{document.documentElement.style.scrollBehavior='auto';scrollTo(0,900)});const y=await page.evaluate(()=>scrollY);await go('servicios.html');await page.goBack({waitUntil:'domcontentloaded'});await settle();assert(Math.abs(await page.evaluate(()=>scrollY)-y)<3);await page.goForward({waitUntil:'domcontentloaded'});assert.match(page.url(),/servicios.html$/);await go('');assert.equal(await page.evaluate(()=>scrollY),0);
await page.setContent('<a target="_blank" href="'+base+'">Abrir AKME desde un chat</a>');const newPage=context.waitForEvent('page');await page.locator('a').click();const opened=await newPage;await opened.waitForLoadState('domcontentloaded');await opened.waitForTimeout(850);assert.equal(await opened.evaluate(()=>scrollY),0);await opened.close();assert.deepEqual(errors,[]);console.log('PASS clean entry, chat new tab, hashes, back/forward, no automatic focus, both clinics and clear return at 320/390/430');
}finally{await browser.close();server.close();}