// Fuente: AKME Cotizador, commit e4aa8b6f97338fada47cc07544f52fb1100684bf.
                                                                          
                                                                                                                                
                                                                                                                                                                                                                                                                                                                  
// Authoritative catalog: user's current akme/index.html, main branch, 2026-10-02.
// Deliverables, prices and service tiers are copied from its package comparison.
export const plans       =[
 {id:"smart",name:"SMART",focus:"Presencia digital",price:1800,videos:2,campaigns:0,arts:4,stories:4,visits:1,equipment:"Móvil premium",community:"No incluido",strategy:"Ficha de marca y planificación básica",measurement:"Reporte de rendimiento",optimization:"No incluida",direction:"No incluida",followup:"Recomendaciones del mes siguiente",level:0,monthly:true,details:["4 artes comerciales · 2 reels · 4 historias","1 jornada de producción de 2 horas","Producción móvil premium","Copywriting básico y ficha de marca","Planificación y reporte de rendimiento","Recomendaciones del mes siguiente"]},
 {id:"esencial",name:"ESENCIAL",focus:"Contenido + publicidad",price:2500,videos:4,campaigns:1,arts:6,stories:6,visits:1,equipment:"Móvil premium + luz",community:"Básico",strategy:"Brief de contenido y calendario mensual",measurement:"Análisis de contenido y publicidad",optimization:"Básica de perfil",direction:"No incluida",followup:"Recomendaciones de mejora",level:1,monthly:true,details:["6 artes comerciales · 4 reels · 6 historias","1 jornada de producción de hasta 2 horas","Producción móvil premium + luz","Brief de contenido y calendario mensual","Gestión de hasta 1 campaña de Meta Ads","Community básico y optimización de perfil","Análisis de contenido y publicidad"]},
 {id:"completo",name:"COMPLETO",focus:"Gestión + optimización",price:3900,videos:6,campaigns:2,arts:9,stories:8,visits:1,equipment:"Híbrida: iPhone + Canon R50",community:"Incluido",strategy:"Brief, diagnóstico, calendario y objetivos",measurement:"Análisis de datos, benchmark e informe",optimization:"Mensual de contenido y campañas",direction:"Básica + guía visual de redes",followup:"1 reunión mensual",level:2,monthly:true,details:["9 artes comerciales · 6 reels · 8 historias","1 jornada de producción de 2 horas","Producción híbrida: iPhone + Canon R50","Brief, diagnóstico, calendario y objetivos","Gestión de hasta 2 campañas de Meta Ads","Community management y optimización mensual","Dirección creativa básica y guía visual","Benchmark, informe y 1 reunión mensual"]},
 {id:"pro",name:"PRO",focus:"Dirección + crecimiento",price:4900,videos:8,campaigns:4,arts:11,stories:11,visits:2,equipment:"Profesional / híbrida",community:"Incluido",strategy:"Brief de marca + marketing y plan mensual",measurement:"Dashboard de marketing y análisis avanzado",optimization:"Embudo digital y proceso de atención",direction:"Incluida",followup:"2 reuniones al mes + seguimiento quincenal",level:3,monthly:true,details:["11 artes comerciales · 8 reels · 11 historias","2 jornadas de producción de 2 horas cada una","Producción profesional o híbrida","Brief de marca + marketing y plan mensual","Gestión de hasta 4 campañas de Meta Ads","Community management y dirección creativa","Dashboard y optimización del embudo","2 reuniones al mes y seguimiento quincenal"]},
 {id:"elite",name:"ELITE",focus:"Dirección integral de marketing",price:7000,videos:11,campaigns:6,arts:15,stories:15,visits:2,equipment:"Profesional avanzada",community:"Prioritario",strategy:"Diagnóstico integral y plan a 90 días",measurement:"Dashboard marketing + ventas e informe ejecutivo",optimization:"Procesos y conversión comercial",direction:"Integral",followup:"1 reunión y seguimiento estratégico semanal",level:4,monthly:true,details:["15 artes comerciales · 11 reels · 15 historias","2 jornadas de producción de 2 horas cada una","Producción profesional avanzada","Diagnóstico integral y plan a 90 días","Gestión de hasta 6 campañas de Meta Ads","Community prioritario y dirección integral","Dashboard marketing + ventas e informe ejecutivo","1 reunión y seguimiento estratégico semanal"]},
];
export const goals=[{id:"presence",title:"Ordenar mi presencia",desc:"Contenido y planificación"},{id:"ads",title:"Sumar publicidad",desc:"Contenido + gestión de Meta Ads"},{id:"optimization",title:"Optimizar mis resultados",desc:"Gestión, análisis y optimización"},{id:"direction",title:"Crecer con dirección",desc:"Estrategia, dashboard y seguimiento"},{id:"integral",title:"Dirección integral",desc:"Marketing y análisis comercial"}]         ;
export const initialNeeds      ={service:"presence",videos:2,campaigns:0,arts:4,stories:4,budget:null,extras:[]};
export const extraLabels                      ={community:"Community management",photos:"Sesión fotográfica adicional",branding:"Branding e identidad",oneoff:"Producción puntual, sin plan mensual"};
export function formatPrice(value            ){return value===null?"A cotizar":`Bs ${value.toLocaleString("es-BO")}`;}
export function gaps(p     ,n      ){const r         =[];const level=goals.findIndex(g=>g.id===n.service);if(p.level<level)r.push(goals[level].title);for(const[key,label]of [["videos","reels"],["campaigns","campañas"],["arts","artes"],["stories","historias"]]        )if(n[key]>p[key])r.push(`${n[key]-p[key]} ${label} adicionales`);if(n.extras.includes("community")&&p.community==="No incluido")r.push("Community management");r.push(...n.extras.filter(x=>x!=="community").map(x=>extraLabels[x]));if(n.budget!==null&&p.price>n.budget)r.push("Supera tu presupuesto");return r;}
export function recommend(n      )                                                   {
 const plan=plans.find(p=>!gaps(p,n).length)??null;
 if(!plan){const scope=plans.find(p=>!gaps(p,{...n,budget:null}).length);return{plan:null,reason:scope&&n.budget!==null?`${scope.name} cubre tus necesidades, pero su precio de ${formatPrice(scope.price)} al mes supera el presupuesto indicado. Podemos revisar el alcance en una propuesta personalizada.`:"Tus necesidades combinan servicios o cantidades que no están cubiertos por un solo plan. Revisemos el alcance en una propuesta personalizada.",budgetUnknown:false};}
 const parts=[n.videos?`${n.videos} reels`:null,n.arts?`${n.arts} artes`:null,n.stories?`${n.stories} historias`:null,n.campaigns?`${n.campaigns} campañas`:null].filter(Boolean);
 return{plan,reason:`Cubre tu objetivo de ${goals.find(g=>g.id===n.service)?.title.toLowerCase()}${parts.length?` y tu selección de ${parts.join(", ")}`:""}. Es el plan de menor precio que reúne todo el alcance solicitado.`,budgetUnknown:false};
}
export function validateNeeds(input        )      {if(!input||typeof input!=="object")throw Error("Selección inválida");const n=input         ;if(!goals.some(g=>g.id===n.service))throw Error("Objetivo inválido");for(const[key,max]of[["videos",16],["campaigns",8],["arts",20],["stories",20]]        )if(!Number.isInteger(n[key])||n[key]<0||n[key]>max)throw Error(`Cantidad inválida: ${key}`);if(n.budget!==null&&(!Number.isFinite(n.budget)||n.budget<0))throw Error("Presupuesto inválido");if(!Array.isArray(n.extras)||n.extras.some(x=>!Object.hasOwn(extraLabels,x))||new Set(n.extras).size!==n.extras.length)throw Error("Servicios adicionales inválidos");return{service:n.service,videos:n.videos,campaigns:n.campaigns,arts:n.arts,stories:n.stories,budget:n.budget,extras:[...n.extras]};}
