const data=await fetch('portfolio.json?v=20261002-editorial3').then(r=>{if(!r.ok)throw Error('No se pudo cargar el portafolio');return r.json();});
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');
const root=document.getElementById('brand-galleries');
root.innerHTML=data.map(brand=>`<section class="brand-gallery" id="proyecto-${brand.id}" aria-labelledby="title-${brand.id}"><header class="gallery-heading"><div><p class="eyebrow">${esc(brand.category)}</p><h2 id="title-${brand.id}">${esc(brand.name)}</h2></div><p>${esc(brand.context)}</p></header><div class="gallery-preview">${brand.items.slice(0,2).map((item,i)=>`<button type="button" class="gallery-card" data-brand="${brand.id}" data-index="${i}" aria-label="Ver ${esc(brand.name)}: ${esc(item.title)}"><span class="gallery-canvas"><img src="${item.poster||item.src}" alt="${esc(item.alt)}" loading="lazy" decoding="async">${item.type==='video'?'<span class="video-mark" aria-hidden="true">▶ Video</span>':'<span class="view-mark" aria-hidden="true">Ampliar</span>'}</span><span class="gallery-caption"><strong>${esc(item.title)}</strong><span>${item.format||(item.type==='video'?'Video':'Diseño')}${item.period?' · '+esc(item.period):''}</span></span></button>`).join('')}</div><div class="gallery-bottom"><p>${esc(brand.note||'')}</p><button type="button" class="btn ghost" data-brand="${brand.id}" data-index="0">Ver galería completa · ${brand.items.length} piezas</button></div></section>`).join('');
const dlg=document.getElementById('gallery-viewer'),media=document.getElementById('gallery-media'),title=document.getElementById('gallery-title'),description=document.getElementById('gallery-description'),count=document.getElementById('gallery-count'),thumbs=document.getElementById('gallery-thumbs');let current,idx=0,opener;
const stop=()=>{const video=media.querySelector('video');if(video){video.pause();video.removeAttribute('src');video.load();}};
function show(){stop();const item=current.items[idx];title.textContent=current.name+' · '+item.title;description.textContent=item.description||current.context;count.textContent=`${idx+1} / ${current.items.length}`;media.replaceChildren();const element=document.createElement(item.type==='video'?'video':'img');if(item.type==='video'){element.controls=true;element.playsInline=true;element.preload='metadata';element.poster=item.poster;element.setAttribute('aria-label',item.title);}else{element.alt=item.alt;}element.src=item.src;media.append(element);thumbs.replaceChildren(...current.items.map((item,i)=>{const b=document.createElement('button');b.type='button';b.textContent=String(i+1).padStart(2,'0');b.setAttribute('aria-label',`Ver pieza ${i+1}: ${item.title}`);b.setAttribute('aria-current',String(idx===i));b.addEventListener('click',()=>{idx=i;show();thumbs.children[i].focus();});return b;}));}
function open(brand,index,source){current=brand;idx=index;opener=source;show();dlg.showModal();dlg.querySelector('.gallery-close').focus();}
root.addEventListener('click',e=>{const b=e.target.closest('[data-brand]');if(!b)return;open(data.find(x=>x.id===b.dataset.brand),Number(b.dataset.index),b);});
document.getElementById('gallery-prev').addEventListener('click',()=>{idx=(idx-1+current.items.length)%current.items.length;show();});document.getElementById('gallery-next').addEventListener('click',()=>{idx=(idx+1)%current.items.length;show();});
dlg.querySelector('.gallery-close').addEventListener('click',()=>dlg.close());dlg.addEventListener('click',e=>{if(e.target===dlg)dlg.close();});dlg.addEventListener('close',()=>{stop();media.replaceChildren();opener?.focus({preventScroll:true});});dlg.addEventListener('keydown',e=>{if(e.target.tagName==='VIDEO')return;if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();idx=(idx+(e.key==='ArrowRight'?1:-1)+current.items.length)%current.items.length;show();}});
document.querySelectorAll('[data-own-images]').forEach(button=>button.addEventListener('click',()=>{const items=button.dataset.ownImages.split(',').map(src=>({type:'image',src,title:button.dataset.title,alt:button.dataset.title,description:'Pieza de comunicación de AKME Estudio.'}));open({name:'Dentro de AKME',items},0,button);}));
// Brand anchors stay usable when galleries are populated after document load.
if(location.hash.startsWith('#proyecto-'))document.getElementById(location.hash.slice(1))?.scrollIntoView();
